services:
  db:
    image: postgres:16
    container_name: finance-db
    environment:
      POSTGRES_DB: financedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: finance-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financedb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: ${ADMIN_PASSWORD}

volumes:
  pgdbdata: